### DISCUSSION TITLE
erro with YAML

### DISCUSSION THREAD

**Discussion by MauroMardones** [nmfs-opensci/quarto-thesis#12] [General]
I render once by when made some changes, I did build again and this error prompt:

ERROR: Project _quarto.yml validation failed.

In file _quarto.yml
(line 54, column 5 through line 56, column 16) Key format has value urlcolor: red
    toclinkcolor: black
    toc-depth: 2, which must be no possible value
53:   quarto-thesis-pdf: 
54:     urlcolor: red
        ~~~~~~~~~~~~~
55:     toclinkcolor: black
    ~~~~~~~~~~~~~~~~~~~~~~~
56:     toc-depth: 2
    ~~~~~~~~~~~~~~~

I didn't change nothing in  `_quarto.yml `

Do you know why?

**Comment by eeholmes** [comment]
What did you change? I'll try to replicate.

**Reply by MauroMardones** [reply]
just I put another name in author, but none change in .yml file. for that is weird the error.

**Comment by eeholmes** [comment]
Another name in author? Author is in _quarto.yml. Can you show me exactly what you did? You can just put the file you changed into the comments. Drag and drop.

<img width="326" alt="image" src="https://user-images.githubusercontent.com/2545978/225994043-34d1d492-8d7b-4545-b6da-0dfc45bdfbca.png">

**Reply by MauroMardones** [reply]
yep, I just change author name, don't add nothing more. Anyway,  the error is in line 52 in `_quarto.yml`  file.

```
# urlcolor changes the url color in the body of the PDF
# linkcolor changes color of internal links (like to figures)
# toclinkcolor changes color of toc, lof and lot links
format:
  quarto-thesis-pdf: 
    urlcolor: red
    toclinkcolor: black
    toc-depth: 2
```

**Comment by eeholmes** [comment]
I cannot replicate the error.  I change the name in _quarto.yml as in the image below but it renders fine. I need to see exactly what you did.

<img width="381" alt="image" src="https://user-images.githubusercontent.com/2545978/226116607-74f1d8a6-0dbd-41d4-a560-4050fa01be42.png">

**Comment by MauroMardones** [comment]
the error is in this part;


```
format:
  quarto-thesis-pdf: 
    urlcolor: red
    toclinkcolor: black
    toc-depth: 3
```

**Reply by MauroMardones** [reply]
ERROR: Project _quarto.yml validation failed.

In file _quarto.yml
(line 54, column 5 through line 56, column 16) Key format has value urlcolor: red
    toclinkcolor: black
    toc-depth: 3, which must be no possible value
53:   quarto-thesis-pdf: 
54:     urlcolor: red
        ~~~~~~~~~~~~~
55:     toclinkcolor: black
    ~~~~~~~~~~~~~~~~~~~~~~~
56:     toc-depth: 3
    ~~~~~~~~~~~~~~~


In file _quarto.yml
(line 54, column 5 through line 56, column 16) Key format has value urlcolor: red
    toclinkcolor: black
    toc-depth: 3, which must be no possible value
53:   quarto-thesis-pdf: 
54:     urlcolor: red
        ~~~~~~~~~~~~~
55:     toclinkcolor: black
    ~~~~~~~~~~~~~~~~~~~~~~~
56:     toc-depth: 3
    ~~~~~~~~~~~~~~~


Exited with status 1.

**Comment by eeholmes** [comment]
This runs fine for me. If your file ran fine and then stopped running when you made a change, it mean I think that your entered a syntax error into the `_quarto.yml` file. I cannot see your files so can't advise unfortunately. If you fork quarto-thesis and push your changes to your own repo and send me that link, I can take a look.
```
project:
  type: book
  output-dir: .

book:
  title: A doctoral thesis title
  author:
    name: Here is another name
    url: http://www.janedoe.com
  cover-image: images/logo.png
  downloads: [pdf]
  abstract: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam quis accumsan ante. Quisque lorem metus, varius id urna eget, lacinia dapibus sem. Etiam laoreet, quam ac mollis congue, arcu leo dictum neque, nec euismod sem enim luctus odio. Donec condimentum tortor sit amet mollis volutpat. Donec ornare libero vel velit malesuada consectetur. Vestibulum in sem non justo dignissim congue at quis erat. Integer quis erat vitae mi maximus fringilla tristique nec odio. Morbi non ipsum sapien. Vestibulum tortor est, ultricies in eros et, bibendum iaculis justo. Cras pellentesque enim quam, id pretium lacus lacinia non. Integer velit neque, ultrices a malesuada vel, imperdiet quis enim. Quisque eu facilisis urna, ut faucibus lorem. Donec mollis turpis sed arcu venenatis interdum. Nulla facilisis tortor ac scelerisque consequat."
  chapters:
    - index.qmd
    - Chapters/Chapter2.qmd
    - references.qmd
  appendices:
    - Appendices/AppendixA.qmd

  site-url: https://nmfs-opensci.github.io/quarto-thesis/
  repo-url: https://github.com/nmfs-opensci/quarto-thesis
  repo-actions: [edit, source, issue]
  search: true

thesis:
  supervisor: 
    name: Dr. Ashok Kunil
    url: https://quarto.org/
  degree-name: Doctor of Philosophy
  university: University of Ottawa
  department: Department of Mathematics
  group: Informatics Program
  faculty: Applied Math Group
  declaration: "Frontmatter/declaration.tex"
  quotation:
    text: "Thanks to my solid academic training, today I can write hundreds of words on virtually any topic without possessing a shred of information, which is how I got a good job in journalism."
    attribution: Dave Barry
  acknowledgements: "Frontmatter/acknowledgements.tex"
  abbreviations: "Frontmatter/abbreviations.tex"
  symbols: "Frontmatter/symbols.tex"
  dedication: "Frontmatter/dedication.tex"

bibliography: [example.bib]

execute:
  echo: false
  code-overflow: wrap

# urlcolor changes the url color in the body of the PDF
# linkcolor changes color of internal links (like to figures)
# toclinkcolor changes color of toc, lof and lot links
format:
  quarto-thesis-pdf: 
    urlcolor: red
    toclinkcolor: black
    toc-depth: 3
```
