### DISCUSSION TITLE
Changing the line spacing only for the main body paragraphs (not tables too)

### DISCUSSION THREAD

**Discussion by eeholmes** [nmfs-opensci/quarto-thesis#7] [Q&A] [answered]
If you use the classoption to change the linespacing, it changes the spacing of tables too. How to you limit the scope?

eg. in `_quarto.yml` you change to onehalfspacing with
```
format:
  quarto-thesis-pdf: 
    urlcolor: red
    toclinkcolor: black
    toc-depth: 2
    classoption: [onehalfspacing, oneside]
```
