### ISSUE TITLE
Template doesnt work with quarto 1.2

### ISSUE THREAD

**Issue by danieltomasz** [nmfs-opensci/quarto-thesis#2]
Quarto 1.2 is in preview but the template is stopping working (all extensions of book class are throwing property error)

**Comment by eeholmes** [comment]
Thanks! Looks like Quarto 1.2 changed on-the-fly meta data definitions. I'll look into how to fix that.

**Comment by danieltomasz** [comment]
I fixed it yesterday myself, the fix is quick, basically the book class cannot have custom fields in quarto 1.2, I renamed those you added both in yml and tex partials, for example now I have `thesis.supervisior` instead of `book.supervisor`
I didn't check if this will work with 1.1x branch.

Thank you for providing this template, I plan to use it to write up my phd :)

**Comment by eeholmes** [comment]
Oh perfect! Can you show me your new `_quarto.yml` code? I spent the morning trying to figure out how to define custom book metadata with no luck. Didn't think to just try adding a new `thesis: ` section.

**Comment by danieltomasz** [comment]
I just copied almost all the custom  fields from book to thesis :) 
(also  I moved custom several files to the `include` folder to have cleaner folder :) ) 
title, author still need to be defined in book fields, here my MVE

```
thesis:
  supervisor:
    name: Best Supervisor
  downloads: [pdf]
  degree-name: Doctor 
  cover-image: include/images/logo.png
  university: My University
  department: Department 
  faculty: Faculty 

book:
  title: Title
  author:
    name: Author Name
```
